### ISSUE TITLE
Missing Posts w/ Reblog + Tag Filtering

### ISSUE THREAD

**Issue by aaroncox** [greymass/reprint#2]
The following post:

https://steemit.com/tag/@walalol/who-am-i

Has been resteemed by the user `giantbear`, but is not displaying in the list of posts. 

The following is the `config.yaml` used:

```
reprint:
  locale: 'en'

blog:
  theme: 'develop'
  title: 'reprint powered blog'
  subtitle: 'blockchain powered blog'
  filters:
    accounts:
      'giantbear':
        - post
        - reblog
    tags:
      - gedwriting

steem:
  host: 'https://node.steem.ws'
```
